import React, { ReactNode, useEffect } from "react";
import Head from "next/head";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer";
import { useRouter } from "next/router";
import { useUserContext } from "@/context/UserProvider";

interface Props {
  children: ReactNode
  isProductPage?: boolean
  isCartPage?: boolean
  isCheckoutPage?: boolean,
  isLoginPage?: boolean,
  isRegisterPage?: boolean,
  headerText?: string,
  isAccountPage?: boolean
}

export default function Layout({
                                 children,
                                 isProductPage = false,
                                 isCartPage = false,
                                 isCheckoutPage = false,
                                 isLoginPage = false,
                                 isRegisterPage = false,
                                 headerText = '',
                                 isAccountPage = false
                               }: Props) {
  const router = useRouter();
  const { signOut } = useUserContext()

  useEffect(() => {
    const handleAlert = async () => {
      if (router?.query?.forceLogout) {
        await signOut()
        alert("Phiên đăng nhập đã hết hạn!")
      }
    }
    handleAlert()
  }, [router?.query?.forceLogout, signOut]);
  return (
    <>
      <Head>
        <title>My app</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Header isProductPage={isProductPage} isCartPage={isCartPage} isCheckoutPage={isCheckoutPage}
              isLoginPage={isLoginPage} isRegisterPage={isRegisterPage} isAccountPage={isAccountPage}
              headerText={headerText}/>
      {children}
      <Footer/>
    </>
  )
}
